language: python
python:
  - "3.4"

services:
  - docker

before_install:
 - docker build

script:
 - docker run python manage.py test

after_success:
 # if [ "$TRAVIS_BRANCH" == "master" ]; then
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" registry.heroku.com
    docker push geniale-cms/web;
   # fi

env:
 - POSTGRES_HOST=localhost

