language: minimal

services:
  - docker

before_install:
 - cp env.docker-example .envdoc
 - docker build -t registry.heroku.com/geniale-cms/web .
 - docker-compose build

script:
 - docker-compose run web  sh "python manage.py test"
 - echo $TRAVIS_PULL_REQUEST_BRANCH && echo $TRAVIS_BRANCH

after_success:
 - |
   if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" registry.heroku.com
      docker push registry.heroku.com/geniale-cms/web
   fi