language: minimal

services:
  - docker

before_install:
 - cp .env.docker-example .env
 - docker build -t registry.heroku.com/geniale-cms/web .
 - docker-compose build

script:
 - docker-compose run web sh -c "python manage.py test"
 - echo $TRAVIS_PULL_REQUEST_BRANCH && echo $TRAVIS_BRANCH

after_success:
 - |
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" registry.heroku.com --password-stdin
    docker push registry.heroku.com/geniale-cms/web