language: python
python:
  - "3.4"

services:
  - docker

before_install:
 - touch .env
 - sudo /etc/init.d/postgresql stop
 - docker build -t geniale-cms/web .
 - docker-compose build

script:
 - docker-compose run web  bash -c "sh ./bin/wait-for-postgres.sh db && python manage.py test"
 - echo $TRAVIS_PULL_REQUEST_BRANCH && echo $TRAVIS_BRANCH

after_success:
 - |
   if [[ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ]]; then
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" registry.heroku.com
      docker push geniale-cms/web
   fi

