version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres
    environment:
        # Make sure the credentials are the same as the default one in the settings.py
        POSTGRES_PASSWORD: 'geniale'
        POSTGRES_USER: 'postgres'