version: '3.3'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: gunicorn --config gunicorn.conf website.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_files:/usr/src/app/static
      - ./media:/usr/src/app/media
    expose:
      - 8000
    env_file: .env
    environment:
      DEBUG: 0
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
    env_file: .env
  nginx:
    build: docker/nginx
    volumes:
      - static_files:/usr/src/app/static
      - ./media:/usr/src/app/media
    ports:
      - 1337:80
    depends_on:
      - web
volumes:
  static_files:
