version: '3.3'

services:
  web:
    volumes:
      - .:/usr/src/app/
    environment:
      DEBUG: 1
  db:
    image: postgres
    volumes:
      - ./pgdata_dev:/var/lib/postgresql/data/pgdata_dev
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata_dev"
