# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-13 13:51
from __future__ import unicode_literals

from django.db import migrations


def load_data(apps, schema_editor):
    BeerContainer = apps.get_model("beer_carousel", "BeerContainer")

    BeerContainer(name="Can", css_class="can").save()
    BeerContainer(name="Bottle", css_class="bottle").save()


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
