# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-13 13:51
from __future__ import unicode_literals

from django.db import migrations


def load_data(apps, schema_editor):
    MemberExtraInfoType = apps.get_model("teamModule", "MemberExtraInfoType")
    models_to_add = [
        MemberExtraInfoType(description="Code permanent"),
        MemberExtraInfoType(description="Code universel"),
        MemberExtraInfoType(description="Niveau scolaire"),
        MemberExtraInfoType(description="En stage"),
        MemberExtraInfoType(description="Numnéro de téléphone")
    ]

    for model in models_to_add:
        model.save()


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
