# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-13 13:51
from __future__ import unicode_literals

from django.db import migrations


def load_data(apps, schema_editor):
  MemberExtraInfoType = apps.get_model("teamModule", "MemberExtraInfoType")
  models_to_add = [
    MemberExtraInfoType(description="Username Github", code='github'),
    MemberExtraInfoType(description="Username Trello", code='trello'),
  ]

  for model in models_to_add:
    model.save()


class Migration(migrations.Migration):
  dependencies = [
    ('website', '0002_add_default_member_extra_fields'),
    ('teamModule', '0020_memberextrainfotype_code')
  ]

  operations = [
    migrations.RunPython(load_data)
  ]
