# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0018_pagenode'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeerCarouselPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='beer_carousel_beercarouselpluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('template', models.CharField(choices=[('beer_carousel/default.html', 'Default')], default='beer_carousel/default.html', editable=False, max_length=255)),
            ],
            options={
                'verbose_name': 'Beer carousel plugin',
                'verbose_name_plural': 'Beer carousel plugins',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='BeerCarouselPluginTranslationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': "Beer carousel' translations",
                'verbose_name': "Beer carousel's translations",
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='BeerCarouselPluginTranslationModelTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Beers', max_length=255)),
                ('creation_date', models.CharField(default='Created', max_length=255)),
                ('type', models.CharField(default='Type', max_length=255)),
                ('alcohol_percent', models.CharField(default='Alcohol %', max_length=255)),
                ('service_temperature', models.CharField(default='Service temperature', max_length=255)),
                ('ibu', models.CharField(default='IBU', max_length=255)),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='beer_carousel.BeerCarouselPluginTranslationModel')),
            ],
            options={
                'db_table': 'beer_carousel_beercarouselplugintranslationmodel_translation',
                'abstract': False,
                'managed': True,
                'db_tablespace': '',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='BeerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alcohol_percent', models.IntegerField()),
                ('ibu', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('type', models.CharField(max_length=100)),
                ('service_temperature', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BeerTranslationsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
                'base_manager_name': '_plain_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='BeerTranslationsModelTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='beer_carousel.BeerTranslationsModel')),
            ],
            options={
                'db_table': 'beer_carousel_beertranslationsmodel_translation',
                'abstract': False,
                'managed': True,
                'db_tablespace': '',
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='beermodel',
            name='translations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beer_carousel.BeerTranslationsModel'),
        ),
        migrations.AddField(
            model_name='beercarouselpluginmodel',
            name='translations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beer_carousel.BeerCarouselPluginTranslationModel'),
        ),
        migrations.AlterUniqueTogether(
            name='beertranslationsmodeltranslation',
            unique_together=set([('language_code', 'master')]),
        ),
        migrations.AlterUniqueTogether(
            name='beercarouselplugintranslationmodeltranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
