# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-10 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
  dependencies = [
    ('beer_carousel', '0003_auto_20180610_1258'),
  ]

  operations = [
    migrations.AddField(
      model_name='beermodel',
      name='image_shift',
      field=models.FloatField(default=0),
    ),
    migrations.AddField(
      model_name='beermodel',
      name='image_size',
      field=models.FloatField(default=30),
    ),
    migrations.AlterField(
      model_name='beermodel',
      name='beer_container',
      field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                              to='beer_carousel.BeerContainer'),
    ),
  ]
