# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-10 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beer_carousel', '0004_auto_20180610_1342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beercarouselpluginmodel',
            options={'verbose_name': "Beer carousel's plugin", 'verbose_name_plural': "Beer carousel's plugins"},
        ),
        migrations.AlterModelOptions(
            name='beercarouselplugintranslationmodel',
            options={'verbose_name': "Beer carousel's translation", 'verbose_name_plural': "Beer carousel's translations"},
        ),
    ]
