# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-10 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ('beer_carousel', '0005_auto_20180610_1354'),
  ]

  operations = [
    migrations.RemoveField(
      model_name='beermodel',
      name='image_size',
    ),
    migrations.AddField(
      model_name='beermodel',
      name='image_scale',
      field=models.FloatField(default=3),
    ),
  ]
