# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
  dependencies = [
    ('teamModule', '0002_auto_20180201_1518'),
  ]

  operations = [
    migrations.CreateModel(
      name='MemberExtraInfo',
      fields=[
        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('value', models.CharField(max_length=500)),
      ],
    ),
    migrations.CreateModel(
      name='MemberExtraInfoType',
      fields=[
        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('description', models.CharField(max_length=50)),
      ],
    ),
    migrations.AddField(
      model_name='memberextrainfo',
      name='info_type',
      field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT,
                              to='teamModule.MemberExtraInfoType'),
    ),
    migrations.AddField(
      model_name='member',
      name='extraInfos',
      field=models.ManyToManyField(to='teamModule.MemberExtraInfo'),
    ),
  ]
