# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 01:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
  dependencies = [
    ('teamModule', '0003_auto_20180225_1236'),
  ]

  operations = [
    migrations.RemoveField(
      model_name='member',
      name='extraInfos',
    ),
    migrations.AddField(
      model_name='memberextrainfo',
      name='member',
      field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teamModule.Member'),
    ),
  ]
