# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ('teamModule', '0004_auto_20180307_2032'),
  ]

  operations = [
    migrations.AlterField(
      model_name='teamdisplayview',
      name='css_class_prefix',
      field=models.CharField(blank=True, default='', max_length=100),
    ),
  ]
