# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamModule', '0005_auto_20180307_2056'),
        ('teamModule', '0004_auto_20180301_2034'),
    ]

    operations = [
    ]
