# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 01:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_auto_20180404_2127'),
        ('teamModule', '0006_merge_20180317_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamBannerModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='teammodule_teambannermodel', serialize=False, to='cms.CMSPlugin')),
                ('template', models.CharField(choices=[('teamModule/member_banner.html', 'Default')], default='teamModule/member_banner.html', editable=False, max_length=255)),
                ('team_image', models.ImageField(upload_to='media/')),
            ],
            options={
                'verbose_name_plural': 'TeamModule Team Banners',
                'verbose_name': 'TeamModule Team Banner',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='TeamBannerTranslationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'TeamModule Team Banners',
                'verbose_name': 'TeamModule Team Banner',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TeamBannerTranslationModelTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.CharField(max_length=255)),
                ('member_description', models.CharField(max_length=255)),
                ('member_more_detail', models.CharField(max_length=255)),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='teamModule.TeamBannerTranslationModel')),
            ],
            options={
                'db_table': 'teamModule_teambannertranslationmodel_translation',
                'managed': True,
                'abstract': False,
                'db_tablespace': '',
                'default_permissions': (),
            },
        ),
        migrations.AlterField(
            model_name='teamdisplayview',
            name='template',
            field=models.CharField(choices=[('teamModule/team_display.html', 'Default'), ('components/member_count.html', 'Total member count')], default='teamModule/team_display.html', max_length=255),
        ),
        migrations.AddField(
            model_name='teambannermodel',
            name='translations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamModule.TeamBannerTranslationModel'),
        ),
        migrations.AlterUniqueTogether(
            name='teambannertranslationmodeltranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
