# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-08 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamModule', '0007_auto_20180404_2127'),
        ('teamModule', '0007_auto_20180402_2036'),
    ]

    operations = [
    ]
