# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamModule', '0009_auto_20180410_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='teambannermodel',
            name='details_button_link',
            field=models.CharField(default='#', max_length=255),
        ),
    ]
