# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-26 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('teamModule', '0010_auto_20180411_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDisplayTranslationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'ProjectDisplay Translation model',
                'verbose_name_plural': 'ProjectDisplay Translation models',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDisplayTranslationModelTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='projects', max_length=255)),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='teamModule.ProjectDisplayTranslationModel')),
            ],
            options={
                'abstract': False,
                'db_table': 'teamModule_projectdisplaytranslationmodel_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='projectdisplayview',
            name='translations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teamModule.ProjectDisplayTranslationModel'),
        ),
        migrations.AlterUniqueTogether(
            name='projectdisplaytranslationmodeltranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
