# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamModule', '0011_auto_20180526_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdisplaytranslationmodeltranslation',
            name='project_name',
        ),
        migrations.AddField(
            model_name='projectdisplaytranslationmodeltranslation',
            name='project_description_title',
            field=models.CharField(default='Project Title', max_length=255),
        ),
        migrations.AddField(
            model_name='projectdisplaytranslationmodeltranslation',
            name='project_status_title',
            field=models.CharField(default='Status', max_length=255),
        ),
        migrations.AddField(
            model_name='projectdisplaytranslationmodeltranslation',
            name='project_title',
            field=models.CharField(default='Project Title', max_length=255),
        ),
        migrations.AddField(
            model_name='projectdisplaytranslationmodeltranslation',
            name='project_website_title',
            field=models.CharField(default='Website', max_length=255),
        ),
        migrations.AddField(
            model_name='projectdisplaytranslationmodeltranslation',
            name='projects_title',
            field=models.CharField(default='Our Projects', max_length=255),
        ),
    ]
