# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamModule', '0010_teambannermodel_details_button_link'),
        ('teamModule', '0011_auto_20180527_1757'),
    ]

    operations = [
    ]
