# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ('teamModule', '0013_auto_20180620_1441'),
  ]

  operations = [
    migrations.AlterField(
      model_name='projectdisplaytranslationmodeltranslation',
      name='project_description_title',
      field=models.CharField(default='Project Description', max_length=255),
    ),
  ]
