# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-24 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ('teamModule', '0014_auto_20180625_0941'),
  ]

  operations = [
    migrations.AddField(
      model_name='project',
      name='display_banner_height',
      field=models.IntegerField(default=0),
    ),
    migrations.AddField(
      model_name='project',
      name='display_order',
      field=models.IntegerField(default=0),
    ),
  ]
