# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-28 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):
  dependencies = [
    ('teamModule', '0016_auto_20190427_1057'),
  ]

  operations = [
    migrations.CreateModel(
      name='FormationTranslation',
      fields=[
        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('name', models.CharField(max_length=100)),
        ('url', models.CharField(blank=True, max_length=200, null=True)),
        ('language_code', models.CharField(db_index=True, max_length=15)),
      ],
      options={
        'db_table': 'teamModule_formation_translation',
        'db_tablespace': '',
        'abstract': False,
        'managed': True,
        'default_permissions': (),
      },
    ),
    migrations.CreateModel(
      name='MemberTranslation',
      fields=[
        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('bio', models.CharField(blank=True, max_length=400)),
        ('language_code', models.CharField(db_index=True, max_length=15)),
      ],
      options={
        'db_table': 'teamModule_member_translation',
        'db_tablespace': '',
        'abstract': False,
        'managed': True,
        'default_permissions': (),
      },
    ),
    migrations.CreateModel(
      name='ProjectStatusTranslation',
      fields=[
        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('status', models.CharField(max_length=20)),
        ('language_code', models.CharField(db_index=True, max_length=15)),
      ],
      options={
        'db_table': 'teamModule_projectstatus_translation',
        'db_tablespace': '',
        'abstract': False,
        'managed': True,
        'default_permissions': (),
      },
    ),
    migrations.CreateModel(
      name='ProjectTranslation',
      fields=[
        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('description', models.TextField(null=True)),
        ('language_code', models.CharField(db_index=True, max_length=15)),
      ],
      options={
        'db_table': 'teamModule_project_translation',
        'db_tablespace': '',
        'abstract': False,
        'managed': True,
        'default_permissions': (),
      },
    ),
    migrations.CreateModel(
      name='TeamRoleTranslation',
      fields=[
        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('role', models.CharField(max_length=100)),
        ('description', models.CharField(blank=True, max_length=1000, null=True)),
        ('language_code', models.CharField(db_index=True, max_length=15)),
      ],
      options={
        'db_table': 'teamModule_teamrole_translation',
        'db_tablespace': '',
        'abstract': False,
        'managed': True,
        'default_permissions': (),
      },
    ),
    migrations.CreateModel(
      name='TeamTranslation',
      fields=[
        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('team_name', models.CharField(max_length=100)),
        ('language_code', models.CharField(db_index=True, max_length=15)),
      ],
      options={
        'db_table': 'teamModule_team_translation',
        'db_tablespace': '',
        'abstract': False,
        'managed': True,
        'default_permissions': (),
      },
    ),
    migrations.AlterModelOptions(
      name='formation',
      options={'base_manager_name': '_plain_manager'},
    ),
    migrations.AlterModelOptions(
      name='member',
      options={'base_manager_name': '_plain_manager'},
    ),
    migrations.AlterModelOptions(
      name='project',
      options={'base_manager_name': '_plain_manager'},
    ),
    migrations.AlterModelOptions(
      name='team',
      options={'base_manager_name': '_plain_manager'},
    ),
    migrations.AlterModelOptions(
      name='teamrole',
      options={'base_manager_name': '_plain_manager'},
    ),
    migrations.AlterModelManagers(
      name='formation',
      managers=[
        ('objects', django.db.models.manager.Manager()),
        ('_plain_manager', django.db.models.manager.Manager()),
      ],
    ),
    migrations.AlterModelManagers(
      name='member',
      managers=[
        ('objects', django.db.models.manager.Manager()),
        ('_plain_manager', django.db.models.manager.Manager()),
      ],
    ),
    migrations.AlterModelManagers(
      name='project',
      managers=[
        ('objects', django.db.models.manager.Manager()),
        ('_plain_manager', django.db.models.manager.Manager()),
      ],
    ),
    migrations.AlterModelManagers(
      name='projectstatus',
      managers=[
        ('objects', django.db.models.manager.Manager()),
        ('_plain_manager', django.db.models.manager.Manager()),
      ],
    ),
    migrations.AlterModelManagers(
      name='team',
      managers=[
        ('objects', django.db.models.manager.Manager()),
        ('_plain_manager', django.db.models.manager.Manager()),
      ],
    ),
    migrations.AlterModelManagers(
      name='teamrole',
      managers=[
        ('objects', django.db.models.manager.Manager()),
        ('_plain_manager', django.db.models.manager.Manager()),
      ],
    ),
    migrations.RemoveField(
      model_name='formation',
      name='name',
    ),
    migrations.RemoveField(
      model_name='formation',
      name='url',
    ),
    migrations.RemoveField(
      model_name='member',
      name='bio',
    ),
    migrations.RemoveField(
      model_name='project',
      name='description',
    ),
    migrations.RemoveField(
      model_name='projectstatus',
      name='status',
    ),
    migrations.RemoveField(
      model_name='team',
      name='team_name',
    ),
    migrations.RemoveField(
      model_name='teamrole',
      name='description',
    ),
    migrations.RemoveField(
      model_name='teamrole',
      name='role',
    ),
    migrations.AddField(
      model_name='teamtranslation',
      name='master',
      field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE,
                              related_name='translations', to='teamModule.Team'),
    ),
    migrations.AddField(
      model_name='teamroletranslation',
      name='master',
      field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE,
                              related_name='translations', to='teamModule.TeamRole'),
    ),
    migrations.AddField(
      model_name='projecttranslation',
      name='master',
      field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE,
                              related_name='translations', to='teamModule.Project'),
    ),
    migrations.AddField(
      model_name='projectstatustranslation',
      name='master',
      field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE,
                              related_name='translations', to='teamModule.ProjectStatus'),
    ),
    migrations.AddField(
      model_name='membertranslation',
      name='master',
      field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE,
                              related_name='translations', to='teamModule.Member'),
    ),
    migrations.AddField(
      model_name='formationtranslation',
      name='master',
      field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE,
                              related_name='translations', to='teamModule.Formation'),
    ),
    migrations.AlterUniqueTogether(
      name='teamtranslation',
      unique_together=set([('language_code', 'master')]),
    ),
    migrations.AlterUniqueTogether(
      name='teamroletranslation',
      unique_together=set([('language_code', 'master')]),
    ),
    migrations.AlterUniqueTogether(
      name='projecttranslation',
      unique_together=set([('language_code', 'master')]),
    ),
    migrations.AlterUniqueTogether(
      name='projectstatustranslation',
      unique_together=set([('language_code', 'master')]),
    ),
    migrations.AlterUniqueTogether(
      name='membertranslation',
      unique_together=set([('language_code', 'master')]),
    ),
    migrations.AlterUniqueTogether(
      name='formationtranslation',
      unique_together=set([('language_code', 'master')]),
    ),
  ]
