# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-10 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamModule', '0019_auto_20190707_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberextrainfotype',
            name='code',
            field=models.CharField(default='Enter a unique code', max_length=50),
        ),
    ]
