# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-15 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamModule', '0020_memberextrainfotype_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
