# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-02-24 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamModule', '0021_project_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='old_member',
            field=models.BooleanField(default=False),
        ),
    ]
