# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-03-25 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamModule', '0022_member_old_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='old_member',
        ),
        migrations.AddField(
            model_name='teamdisplaytranslationmodeltranslation',
            name='old_members_title',
            field=models.CharField(default='Old Members', max_length=255),
        ),
    ]
