# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-03-25 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamModule', '0023_auto_20210324_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamdisplaytranslationmodeltranslation',
            name='old_members_title',
            field=models.CharField(default='Former Members', max_length=255),
        ),
    ]
