version: '3.3'

services:
  db:
    image: postgres
    restart: always
    environment:
      # Make sure the credentials are the same as the default one in the settings.py
      POSTGRES_PASSWORD: 'geniale'
      POSTGRES_USER: 'postgres'
    ports:
      - 5432:5432
