# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        #('cms', '0019_auto_20180327_0739'),
        ('teamModule', '0006_merge_20180317_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDisplayView',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='teammodule_projectdisplayview', serialize=False, to='cms.CMSPlugin')),
                ('template', models.CharField(choices=[('projectModule/project_display.html', 'project_display.html')], default='projectModule/project_display.html', editable=False, max_length=255)),
                ('css_class_prefix', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name': 'TeamModule Project Display',
                'verbose_name_plural': 'TeamModule Project Displays',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AlterField(
            model_name='teamdisplayview',
            name='template',
            field=models.CharField(choices=[('teamModule/team_display.html', 'team_display.html'), ('components/member_count.html', 'Total member count')], default='teamModule/team_display.html', max_length=255),
        ),
    ]
