# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
  dependencies = [
    ('sponsorsModule', '0001_initial'),
  ]

  operations = [
    migrations.AddField(
      model_name='categorytranslation',
      name='category',
      field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE,
                              to='sponsorsModule.Category'),
      preserve_default=False,
    ),
    migrations.AddField(
      model_name='sponsor',
      name='score',
      field=models.IntegerField(default=1),
      preserve_default=False,
    ),
  ]
