# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
  dependencies = [
    ('sponsorsModule', '0002_auto_20180527_2037'),
  ]

  operations = [
    migrations.CreateModel(
      name='CategoryTranslationTranslation',
      fields=[
        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('name', models.CharField(default='Gold', max_length=255)),
        ('language_code', models.CharField(db_index=True, max_length=15)),
      ],
      options={
        'db_tablespace': '',
        'db_table': 'sponsorsModule_categorytranslation_translation',
        'managed': True,
        'default_permissions': (),
        'abstract': False,
      },
    ),
    migrations.AlterModelOptions(
      name='categorytranslation',
      options={'verbose_name': 'Category Translation model',
               'verbose_name_plural': 'Categories Translation models'},
    ),
    migrations.RemoveField(
      model_name='categorytranslation',
      name='category',
    ),
    migrations.RemoveField(
      model_name='categorytranslation',
      name='name',
    ),
    migrations.AddField(
      model_name='category',
      name='translation',
      field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                              to='sponsorsModule.CategoryTranslation'),
      preserve_default=False,
    ),
    migrations.AddField(
      model_name='categorytranslationtranslation',
      name='master',
      field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE,
                              related_name='translations', to='sponsorsModule.CategoryTranslation'),
    ),
    migrations.AlterUniqueTogether(
      name='categorytranslationtranslation',
      unique_together=set([('language_code', 'master')]),
    ),
  ]
