# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('sponsorsModule', '0003_auto_20180605_2122'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='categorytranslation',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AlterField(
            model_name='category',
            name='translation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sponsorsModule.CategoryTranslation'),
        ),
    ]
