# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-07 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ('sponsorsModule', '0004_auto_20180605_2145'),
  ]

  operations = [
    migrations.AlterModelOptions(
      name='category',
      options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
    ),
    migrations.AddField(
      model_name='sponsorsdisplayview',
      name='categories',
      field=models.ManyToManyField(to='sponsorsModule.Category'),
    ),
    migrations.AlterField(
      model_name='categorytranslationtranslation',
      name='name',
      field=models.CharField(max_length=255),
    ),
  ]
